# Generated by Django 5.2.8 on 2026-01-10 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('short_description', models.CharField(max_length=300, verbose_name='short description')),
                ('full_description', models.TextField(verbose_name='full description')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
    ]
