# Generated by Django 5.2.8 on 2026-01-10 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('stars', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'perfect')], max_length=1, verbose_name='stars')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('Archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_comments', to='archives.archives', verbose_name='archive')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'CommentArchive',
                'verbose_name_plural': 'CommentArchives',
            },
        ),
    ]
