# Generated by Django 5.2.8 on 2026-01-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_commentarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentarchive',
            old_name='Archive',
            new_name='archive',
        ),
    ]
