# Generated by Django 5.2.8 on 2026-02-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_rename_archive_commentarchive_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentarchive',
            options={'ordering': ['-datetime_modified'], 'verbose_name': 'CommentArchive', 'verbose_name_plural': 'CommentArchives'},
        ),
    ]
