# Generated by Django 5.2.8 on 2026-02-11 16:46

import articles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=articles.models.Article_image_upload_to, verbose_name='image')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('category', models.CharField(max_length=70, verbose_name='category')),
                ('text', models.TextField(verbose_name='text')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
