# Generated by Django 5.2.8 on 2026-02-18 19:34

import articles.models
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=articles.models.article_image_upload_to, verbose_name='image')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('category', models.CharField(choices=[('Renovation', 'Renovation'), ('Cabinet', 'Cabinet'), ('Knauf', 'Knauf'), ('InteriorDesign', 'Interior Design'), ('Other', 'Other')], max_length=20, verbose_name='category')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('short_text', models.CharField(max_length=50, verbose_name='short text')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('stars', models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'perfect')], verbose_name='stars')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Comment Article',
                'verbose_name_plural': 'Comments Article',
                'ordering': ['-datetime_modified'],
            },
        ),
    ]
