# Generated by Django 5.2.8 on 2026-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_text',
            field=models.CharField(default='hello', max_length=50, verbose_name='short_text'),
            preserve_default=False,
        ),
    ]
