# Generated by Django 5.2.8 on 2026-02-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_short_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='commentarticle',
            options={'ordering': ['-datetime_modified'], 'verbose_name': 'Comment Article', 'verbose_name_plural': 'Comments Article'},
        ),
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.CharField(max_length=50, verbose_name='short text'),
        ),
    ]
