# Generated by Django 5.2.8 on 2026-01-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='is paid')),
                ('last_name', models.CharField(max_length=30, verbose_name='is paid')),
                ('city', models.CharField(max_length=70, verbose_name='is paid')),
                ('note', models.TextField(verbose_name='is paid')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
            ],
        ),
    ]
