# Generated by Django 5.2.8 on 2026-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('note', models.TextField(verbose_name='note')),
            ],
        ),
        migrations.AlterField(
            model_name='consulting',
            name='city',
            field=models.CharField(max_length=70, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='note',
            field=models.TextField(verbose_name='note'),
        ),
    ]
