# Generated by Django 5.2.8 on 2026-02-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactus_alter_consulting_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulting',
            options={'verbose_name': 'Consulting', 'verbose_name_plural': 'Consultings'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'ContactUss'},
        ),
    ]
