# Generated by Django 5.2.8 on 2026-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_consulting_options_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='area_size',
            field=models.PositiveIntegerField(default=0, verbose_name='area size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulting',
            name='contact_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('noon', 'Noon'), ('evening', 'Evening')], default='morning', max_length=10, verbose_name='contact_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulting',
            name='service_type',
            field=models.CharField(choices=[('cabinet', 'Cabinet'), ('tile', 'Tile'), ('decoration', 'Decoration Change'), ('knauf', 'Knauf'), ('renovation', 'Full Renovation')], default='cabinet', max_length=20, verbose_name='service type'),
            preserve_default=False,
        ),
    ]
