# Generated by Django 5.2.8 on 2026-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_consulting_area_size_consulting_contact_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='contact_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('noon', 'Noon'), ('evening', 'Evening')], max_length=10, verbose_name='contacttime'),
        ),
    ]
