# Generated by Django 5.2.8 on 2026-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_consulting_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='area_size',
            field=models.PositiveIntegerField(default=0, verbose_name='area size'),
        ),
    ]
