# Generated by Django 5.2.8 on 2025-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('full_description', models.TextField(verbose_name='Full Description')),
            ],
        ),
    ]
