# Generated by Django 5.2.8 on 2026-02-18 09:26

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cabinet', 'Cabinet'), ('knauf', 'Knauf'), ('decoration', 'Decoration')], max_length=20, verbose_name='service type')),
                ('image', models.ImageField(upload_to=services.models.services_image_upload_to, verbose_name='image')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
            ],
        ),
    ]
