# Generated by Django 5.2.8 on 2025-12-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
