# Generated by Django 5.2.8 on 2025-12-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesimage',
            options={'verbose_name': 'ServiceImage', 'verbose_name_plural': 'ServiceImages'},
        ),
        migrations.RemoveField(
            model_name='servicesimage',
            name='product',
        ),
        migrations.AddField(
            model_name='servicesimage',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.servicesmodel', verbose_name='service'),
            preserve_default=False,
        ),
    ]
