# Generated by Django 5.2.8 on 2025-12-04 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_options_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 4, 11, 7, 16, 63191, tzinfo=datetime.timezone.utc), verbose_name='datetime created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime modified'),
        ),
    ]
