# Generated by Django 5.2.8 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentproduct',
            options={'ordering': ['-datetime_modified'], 'verbose_name': 'CommentProduct', 'verbose_name_plural': 'CommentProducts'},
        ),
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='product/main_image/product_image', verbose_name='main image'),
        ),
    ]
