# Generated by Django 5.2.8 on 2026-02-09 18:12

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_commentproduct_options_products_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='diameter (cm):'),
        ),
        migrations.AddField(
            model_name='products',
            name='edge_type',
            field=models.CharField(blank=True, choices=[('polished', 'polished'), ('beveled', 'beveled'), ('flat', 'flat')], default='polished', max_length=20, verbose_name='edge type'),
        ),
        migrations.AddField(
            model_name='products',
            name='glass_thickness',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='glass thickness (mm):'),
        ),
        migrations.AddField(
            model_name='products',
            name='suitable_for',
            field=models.CharField(blank=True, help_text='Separate locations with a comma (e.g., Restroom, Living room)', max_length=255, verbose_name='suitable for'),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('decorative', 'decorative'), ('modern', 'modern'), ('custom', 'custom')], default='decorative', max_length=20, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='stars',
            field=models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'perfect')], verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.gallery_upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='height (m):'),
        ),
        migrations.AlterField(
            model_name='products',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='length (m):'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=shop.models.product_upload_to, verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='width (m):'),
        ),
    ]
