# Generated by Django 5.2.8 on 2026-02-11 23:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_commentproduct_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='full description'),
        ),
    ]
